options = 
{
	["playerName"] = "GOOOOOOD MORNING VIETNAM",
	["miscellaneous"] = 
	{
		["chat_window_at_start"] = true,
		["TrackIR_external_views"] = true,
		["f11_free_camera"] = true,
		["f10_awacs"] = true,
		["Coordinate_Display"] = "Precise Lat Long",
		["accidental_failures"] = false,
		["autologin"] = true,
		["show_pilot_body"] = false,
		["collect_stat"] = true,
		["synchronize_controls"] = false,
		["backup"] = true,
		["headmove"] = true,
		["f5_nearest_ac"] = true,
		["F2_view_effects"] = 0,
		["launcher"] = true,
		["allow_server_screenshots"] = true,
		["mgrs_grid_visible"] = false,
		["backupTime"] = 2,
		["geo_grid_visible"] = false,
		["force_feedback_enabled"] = true,
	}, -- end of ["miscellaneous"]
	["difficulty"] = 
	{
		["fuel"] = false,
		["spottingDot"] = 3,
		["miniHUD"] = false,
		["optionsView"] = "optview_all",
		["setGlobal"] = true,
		["avionicsLanguage"] = "native",
		["cockpitVisualRM"] = false,
		["map"] = true,
		["gWarmUp"] = false,
		["spectatorExternalViews"] = true,
		["userSnapView"] = true,
		["iconsTheme"] = "russian",
		["weapons"] = false,
		["padlock"] = false,
		["birds"] = 0,
		["permitCrash"] = true,
		["immortal"] = false,
		["easyCommunication"] = true,
		["wakeTurbulence"] = true,
		["easyFlight"] = false,
		["hideStick"] = false,
		["radio"] = true,
		["geffect"] = "realistic",
		["unrestrictedSATNAV"] = true,
		["reports"] = true,
		["tips"] = true,
		["cockpitStatusBarAllowed"] = false,
		["autoTrimmer"] = false,
		["externalViews"] = true,
		["RBDAI"] = true,
		["controlsIndicator"] = true,
		["units"] = "imperial",
		["userMarks"] = true,
		["labels"] = 3,
	}, -- end of ["difficulty"]
	["VR"] = 
	{
		["handOffsetZ"] = 0,
		["enableHMDMask"] = true,
		["box_mouse_cursor"] = true,
		["handOffsetY"] = 0,
		["mirror_crop"] = false,
		["pointer_use_type"] = 0,
		["mirror_use_DCS_resolution"] = false,
		["openxr_eyeGaze"] = false,
		["hand_controllers_use_throttle"] = true,
		["hand_controllers_joint_throttle"] = false,
		["use_mouse"] = true,
		["openxr_quadView"] = false,
		["custom_IPD_enable"] = false,
		["hand_controllers_type"] = 0,
		["hand_controllers_debug_draw"] = false,
		["handOffsetX"] = 0,
		["prefer_built_in_audio"] = true,
		["pixel_density"] = 1,
		["hand_controllers_use_stick"] = true,
		["msaaMaskSize"] = 0.42,
		["enable"] = false,
		["interaction_with_grip_only"] = false,
		["bloom"] = true,
		["mirror_source"] = 0,
		["custom_IPD"] = 63.5,
		["hand_controllers"] = true,
	}, -- end of ["VR"]
	["graphics"] = 
	{
		["volumetricLights"] = 1,
		["AA"] = "DLAA",
		["forestDetailsFactor"] = 1,
		["rainDroplets"] = 2,
		["LensEffects"] = 3,
		["heatBlr"] = 2,
		["anisotropy"] = 4,
		["water"] = 2,
		["motionBlurAmount"] = 1,
		["scaleGui"] = 1.25,
		["visibRange"] = "Extreme",
		["aspect"] = 2.3888888888889,
		["lights"] = 2,
		["shadows"] = 4,
		["MSAA"] = 2,
		["canopyReflections"] = 1,
		["clutterMaxDistance"] = 1500,
		["textures"] = 2,
		["DLSS_PerfQuality"] = 1,
		["outputGamma"] = 1.7,
		["forestDistanceFactor"] = 1,
		["BlurFlatShadows"] = 1,
		["cockpitGI"] = 1,
		["terrainTextures"] = "max",
		["box_mouse_cursor"] = true,
		["multiMonitorSetup"] = "1camera",
		["messagesFontScale"] = 1.5,
		["defaultFOV"] = 70,
		["shadowTree"] = false,
		["chimneySmokeDensity"] = 10,
		["maxFPS"] = 145,
		["SSS"] = 0,
		["fullScreen"] = false,
		["useDeferredShading"] = 1,
		["effects"] = 3,
		["Scaling"] = 0.66,
		["DOF"] = 0,
		["clouds"] = 3,
		["sceneryDetailsFactor"] = 1,
		["Upscaling"] = "OFF",
		["flatTerrainShadows"] = 1,
		["LODmult"] = 1,
		["secondaryShadows"] = 1,
		["ColorGradingLUT"] = 14,
		["SSLR"] = 1,
		["width"] = 3440,
		["SSAO"] = 1,
		["Sharpening"] = 0,
		["sync"] = false,
		["preloadRadius"] = 150000,
		["height"] = 1440,
		["motionBlur"] = 0,
		["ScreenshotExt"] = "png",
		["civTraffic"] = "low",
	}, -- end of ["graphics"]
	["plugins"] = 
	{
		["CA"] = 
		{
			["kompass_options"] = 1,
			["ground_aim_helper"] = true,
			["ground_automatic"] = true,
			["ground_target_info"] = true,
			["ground_isometric"] = true,
			["ground_engine_autostart"] = true,
			["ground_platform_shake"] = true,
			["automatic_clutch"] = true,
		}, -- end of ["CA"]
		["JF-17"] = 
		{
			["PROG04FLBI"] = 3,
			["PROG04FLN"] = 4,
			["PROG01FLBI"] = 0,
			["DLPOD_TDC"] = 1,
			["PROG04FLI"] = 2,
			["PROG01FLR"] = 1,
			["AntZoomInv"] = false,
			["PROG02CHN"] = 3,
			["PROG04CHBI"] = 3,
			["CPTModel"] = "JF-17-CPT",
			["PROG02CHR"] = 3,
			["PROG01CHI"] = 0,
			["PROG05CHI"] = 1,
			["DMAPTYPE"] = 1,
			["PROG03FLR"] = 2,
			["GUNLIMIT"] = 0,
			["PROG02FLR"] = 1,
			["TVIR_TDC"] = 1,
			["PROG05FLI"] = 1,
			["PROG03FLN"] = 4,
			["CPLocalList"] = "ANIME",
			["FLAREBINGO"] = 8,
			["PROG01FLI"] = 2,
			["PROG04TYPE"] = 1,
			["PROG01CHR"] = 1,
			["TDC_DEADZONE"] = 0.01,
			["PROG05CHN"] = 4,
			["PROG03CHR"] = 1,
			["PROG05FLN"] = 4,
			["PROG01FLN"] = 1,
			["TestingChg"] = true,
			["MITLCTRL"] = 0,
			["PROG02CHI"] = 2,
			["PROG04CHR"] = 1,
			["PROG02FLI"] = 2,
			["PROG02TYPE"] = 0,
			["CHAFFBINGO"] = 10,
			["PROG05CHR"] = 3,
			["RDR_TDC"] = 1,
			["PROG03FLI"] = 3,
			["RDR_ELEV"] = 1,
			["PROG03CHBI"] = 3,
			["PROG01TYPE"] = 2,
			["PROG03CHN"] = 1,
			["HUD_TDC"] = 1,
			["PROG03CHI"] = 2,
			["PROG05FLR"] = 3,
			["PROG05CHBI"] = 0,
			["PROG04CHN"] = 1,
			["PROG02CHBI"] = 3,
			["PROG03TYPE"] = 1,
			["PROG05TYPE"] = 2,
			["PROG05FLBI"] = 0,
			["HiddenStick"] = true,
			["KYBDPITCH"] = 0,
			["PROG01CHN"] = 1,
			["GUNSIGHT"] = 0,
			["PROG01CHBI"] = 0,
			["MUSICNUM_SLIDER"] = 5,
			["PROG02FLN"] = 1,
			["PROG04FLR"] = 3,
			["PROG03FLBI"] = 0,
			["PROG02FLBI"] = 3,
			["WMD_TDC"] = 1,
			["PROG04CHI"] = 2,
			["RemoveProbe"] = false,
			["VOICELOCALE"] = 4,
			["IcingOnCake"] = true,
		}, -- end of ["JF-17"]
		["MovingMap"] = 
		{
			["mmHost"] = "",
		}, -- end of ["MovingMap"]
		["VoiceChat"] = 
		{
			["use_turn_servers_enabled"] = false,
		}, -- end of ["VoiceChat"]
		["VRFree"] = 
		{
			["handUseThrottle"] = false,
			["handUseStick"] = false,
			["set_debug"] = false,
			["enable"] = false,
			["mouseClickSrc"] = 0,
		}, -- end of ["VRFree"]
		["TF-51D"] = 
		{
			["assistance"] = 100,
			["CPLocalList"] = "default",
			["autoRudder"] = false,
		}, -- end of ["TF-51D"]
		["CaptoGlove"] = 
		{
			["fingerPinkyBentRight"] = "0",
			["armBending"] = 60,
			["shoulderJointX_Right"] = -15,
			["fingerPinkyStraightRight"] = "1000",
			["mouseClickSrc"] = 0,
			["shoulderJointZ_Left"] = 23,
			["trackerHMDnameRight"] = "DISABLE",
			["set_attach"] = false,
			["fingerMiddleBentLeft"] = "0",
			["gloveRotationPitch_Left"] = 0,
			["fingerMiddleStraightRight"] = "1000",
			["yawOffsetGlove_Left"] = 0,
			["yawOffsetShoulder_Right"] = 0,
			["fingerThumbStraightLeft"] = "1000",
			["gloveOffsetY_Right"] = 0,
			["gloveOffsetX_Left"] = 0,
			["shoulderJointY_Left"] = -23,
			["gloveRotationYaw_Right"] = 0,
			["trackerHMDnameLeft"] = "DISABLE",
			["set_symmetrically"] = false,
			["fingerIndexStraightRight"] = "1000",
			["pitchOffsetGlove_Right"] = 0,
			["fingerIndexBentRight"] = "0",
			["gloveOffsetZ_Right"] = 0,
			["shoulderJointZ_Right"] = 23,
			["useHMDControl"] = false,
			["pitchOffsetShoulder_Left"] = 0,
			["fingerMiddleStraightLeft"] = "1000",
			["pitchOffsetShoulder_Right"] = 0,
			["fingerRingStraightLeft"] = "1000",
			["fingerThumbBentRight"] = "0",
			["shoulderJointX_Left"] = -15,
			["enable"] = false,
			["gloveOffsetY_Left"] = 0,
			["fingerMiddleBentRight"] = "0",
			["fingerRingBentLeft"] = "0",
			["forearmLength_Right"] = 30,
			["fingerThumbStraightRight"] = "1000",
			["gloveOffsetZ_Left"] = 0,
			["shoulderLength_Right"] = 40,
			["fingerPinkyStraightLeft"] = "1000",
			["gloveRotationYaw_Left"] = 0,
			["gloveRotationPitch_Right"] = 0,
			["forearmLength_Left"] = 30,
			["set_debug"] = false,
			["useBending"] = false,
			["fingerRingBentRight"] = "0",
			["shoulderJointY_Right"] = -23,
			["gloveRotationRoll_Left"] = 0,
			["fingerIndexBentLeft"] = "0",
			["shoulderLength_Left"] = 40,
			["yawOffsetShoulder_Left"] = 0,
			["fingerRingStraightRight"] = "1000",
			["fingerIndexStraightLeft"] = "1000",
			["yawOffsetGlove_Right"] = 0,
			["gloveOffsetX_Right"] = 0,
			["pitchOffsetGlove_Left"] = 0,
			["fingerThumbBentLeft"] = "0",
			["gloveRotationRoll_Right"] = 0,
			["fingerPinkyBentLeft"] = "0",
		}, -- end of ["CaptoGlove"]
		["Ka-50"] = 
		{
			["Ka50TrimmingMethod"] = 0,
			["Ka50RudderTrimmer"] = false,
			["hmdEye"] = 1,
			["CPLocalList"] = "default",
			["helmetCircleDisplacement"] = 11,
		}, -- end of ["Ka-50"]
		["F-15C"] = 
		{
			["CPLocalList"] = "ANIME",
		}, -- end of ["F-15C"]
		["CJS Super Hornets"] = 
		{
			["abDetent"] = 0,
			["canopyReflections"] = 0,
			["hmdEye"] = 1,
			["CPLocalList"] = "default",
			["F18RealisticTDC"] = true,
			["mfdReflections"] = 0,
		}, -- end of ["CJS Super Hornets"]
		["Su-33"] = 
		{
			["CPLocalList"] = "default",
		}, -- end of ["Su-33"]
		["F-14"] = 
		{
			["JESTER_HeadMenu"] = true,
			["FFB_TRIM"] = false,
			["JESTER_LandingCallouts"] = true,
			["AB_GATE"] = false,
			["JESTER_Camera"] = true,
			["RadioMenuPttOptions"] = 0,
			["TID_A2G"] = false,
			["WEAP_OFF_GUN"] = false,
			["WEAP_UP_SPPH"] = false,
			["AOA_BUFFET"] = false,
			["SWEEP_HANDLE_RAISED_COND"] = false,
			["EXT_LIGHT_CATAPULT"] = true,
			["JESTER_SwitchPDSTTToPSTT"] = false,
			["AFTERBURNER_DETENT_VALUE"] = 70,
			["AFTERBURNER_DETENT_DEADZONE"] = 10,
		}, -- end of ["F-14"]
		["UltraLeap"] = 
		{
			["handOffsetY"] = 0,
			["enable"] = false,
			["handUseThrottle"] = false,
			["handOffsetZ"] = 0,
			["handUseStick"] = false,
			["handOffsetX"] = 0,
			["set_debug"] = false,
			["mouseClickSrc"] = 0,
		}, -- end of ["UltraLeap"]
		["DCS-SRS"] = 
		{
			["srsOverlayHelpTextEnabled"] = true,
			["srsOverlayEnabled"] = true,
			["srsAutoLaunchEnabled"] = true,
			["srsOverlayCompactModeEnabled"] = false,
		}, -- end of ["DCS-SRS"]
		["FlankerEx"] = 
		{
			["PROG04FLBI"] = 3,
			["Su30MKMroleType"] = 1,
			["PROG04FLN"] = 4,
			["PROG02FLI"] = 2,
			["CHAFFBINGO"] = 10,
			["PROG03FLI"] = 3,
			["PROG01FLBI"] = 3,
			["Su30SMroleType"] = 1,
			["CPLocalList_Su-30MKI"] = "default",
			["PROG04FLI"] = 2,
			["PROG01FLR"] = 1,
			["PROG05FLR"] = 3,
			["PROG02CHI"] = 2,
			["PROG02TYPE"] = 1,
			["PROG02CHN"] = 3,
			["PROG04CHR"] = 1,
			["PROG01CHN"] = 4,
			["CPLocalList_Su-30MK"] = "default",
			["PROG03FLN"] = 4,
			["Su30MKMfmType"] = 1,
			["PROG02CHR"] = 3,
			["Su30MKMavionicsType"] = 0,
			["PROG05CHR"] = 3,
			["CPLocalList_Su-30SM"] = "default",
			["PROG01CHI"] = 3,
			["PROG05CHI"] = 1,
			["PROG02FLN"] = 1,
			["PROG03FLR"] = 2,
			["PROG04CHBI"] = 3,
			["PROG02FLR"] = 1,
			["PROG01TYPE"] = 3,
			["Su30SMavionicsType"] = 1,
			["PROG03FLBI"] = 0,
			["PROG03CHN"] = 1,
			["PROG05FLI"] = 1,
			["PROG03CHI"] = 2,
			["Su30MKIroleType"] = 1,
			["CPLocalList_Su-30MKM"] = "default",
			["PROG05TYPE"] = 2,
			["PROG04CHN"] = 1,
			["PROG05CHBI"] = 0,
			["FLAREBINGO"] = 10,
			["PROG01CHR"] = 3,
			["Su30MKAavionicsType"] = 0,
			["Su30SMfmType"] = 1,
			["PROG01FLI"] = 2,
			["PROG04TYPE"] = 1,
			["PROG02CHBI"] = 3,
			["PROG05FLBI"] = 0,
			["PROG03CHR"] = 1,
			["Su30MKAfmType"] = 1,
			["Su30MKAroleType"] = 1,
			["Su30MKIavionicsType"] = 0,
			["PROG01CHBI"] = 0,
			["Su30MKIfmType"] = 1,
			["PROG03CHBI"] = 3,
			["PROG04FLR"] = 3,
			["PROG05CHN"] = 4,
			["PROG02FLBI"] = 3,
			["CPLocalList_Su-30MKA"] = "default",
			["PROG04CHI"] = 2,
			["PROG05FLN"] = 4,
			["PROG03TYPE"] = 2,
			["PROG01FLN"] = 1,
		}, -- end of ["FlankerEx"]
		["F/A-18C"] = 
		{
			["abDetent"] = 0,
			["canopyReflections"] = 0,
			["hmdEye"] = 1,
			["CPLocalList"] = "default",
			["F18RealisticTDC"] = true,
			["mfdReflections"] = 0,
		}, -- end of ["F/A-18C"]
		["MiG-29"] = 
		{
			["CPLocalList_MiG-29S"] = "default",
			["CPLocalList_MiG-29G"] = "default",
			["CPLocalList_MiG-29A"] = "default",
		}, -- end of ["MiG-29"]
		["Mi-24P"] = 
		{
			["CPLocalList"] = "default",
			["Mi24AIColorScheme"] = 0,
			["Mi24AIHideBoxes"] = false,
			["Mi24AIVoiceLanguage"] = 0,
			["Mi24PedalsAutoMove"] = true,
			["Mi24AutoHandover"] = true,
			["Mi24PedalsInputSensitivity"] = 24,
			["Mi24StickTrimMethod"] = 0,
			["SPOVolume"] = 100,
			["Mi24PedalsTrimButton"] = 1,
			["Mi24PedalsMicroswitchLogic"] = 1,
			["Aiming_mark"] = false,
			["collectiveDisengage"] = 1,
			["controlHelperMi24"] = false,
			["Mi24CockpitShake"] = 50,
			["Mi24PedalsTrimMode"] = 0,
			["collectiveBrake"] = 0,
			["weapTooltipsMi24"] = true,
		}, -- end of ["Mi-24P"]
		["A-10A"] = 
		{
			["CPLocalList"] = "default",
		}, -- end of ["A-10A"]
		["tu_16"] = {},
		["F-15ESE"] = 
		{
			["RAND_RDR_CHANNEL"] = false,
			["RADAR_SAR_SCINTILLATION"] = true,
			["RADAR_MAX_CORES"] = 4,
			["LINEAR_STICK"] = false,
			["CPLocalList"] = "default",
			["RADALT_ADVANCED"] = false,
			["MONITOR_EYEPOINT_OFFSET"] = 0,
			["THROTTLE_CO_DETENT"] = 10,
			["VR_EYEPOINT_OFFSET"] = 5,
			["FF_TRIM_OFFSET"] = true,
			["THROTTLE_AB_DETENT"] = 75,
			["GHOST_CONTROLS"] = false,
			["FF_PITCH_GAIN"] = 65,
			["FF_ROLL_GAIN"] = 65,
			["LOW_END_TEXT"] = false,
		}, -- end of ["F-15ESE"]
		["A-10C_2"] = 
		{
			["GUNPAC_Runway"] = 0.1,
			["hmdEye"] = 1,
			["CPLocalList"] = "factory_new",
			["throttleSlewMaverick"] = 5,
			["GUNPAC_Hot"] = 0.1,
			["defaultGunMode"] = 0,
			["throttleSlewTGP"] = 5,
			["GUNPAC_Cold"] = 0.1,
			["GUNPAC_Air"] = 0.2,
		}, -- end of ["A-10C_2"]
		["MiG-29-Fulcrum"] = 
		{
			["ThrottleAutoLatch"] = true,
			["MiG29AvionicsLanguage"] = 0,
			["MiG29HUDLanguage"] = 0,
			["CPLocalList"] = "default",
			["MiG29AvionicsPreset"] = 0,
			["MiG29HmdAnimationSKAB"] = true,
			["MiG29SensitivityTDC"] = 20,
			["MiG29HmdMonocleVisible"] = true,
			["MiG29HmdEye"] = 1,
			["MiG29AvionicsUnits"] = 0,
		}, -- end of ["MiG-29-Fulcrum"]
		["A-10C"] = 
		{
			["GUNPAC_Cold"] = 0.1,
			["GUNPAC_Hot"] = 0.1,
			["GUNPAC_Runway"] = 0.1,
			["throttleSlewTGP"] = 5,
			["CPLocalList"] = "default",
			["throttleSlewMaverick"] = 5,
			["GUNPAC_Air"] = 0.2,
		}, -- end of ["A-10C"]
		["F-16C"] = 
		{
			["hmdEye"] = 1,
			["CPLocalList"] = "default",
			["rollForceStickGradient"] = 1,
			["abDetent"] = 0,
			["canopyReflections"] = 1,
			["pitchDeadzoneValue"] = 4.375,
			["rollDeadzoneValue"] = 5.9,
			["mfdReflections"] = 1,
			["canopyTint"] = 1,
			["pitchForceStickGradient"] = 1,
		}, -- end of ["F-16C"]
		["Su-27"] = 
		{
			["CPLocalList"] = "default",
		}, -- end of ["Su-27"]
		["Supercarrier"] = 
		{
			["deck_crew"] = true,
			["enable_FLOLS_overlay"] = true,
			["messages_enabled"] = true,
			["simplified_taxi"] = true,
			["Use_native_ATC_text"] = false,
			["helpers_enabled"] = true,
			["velocity_limit_enabled"] = true,
		}, -- end of ["Supercarrier"]
		["ka_52"] = {},
		["Su-25T"] = 
		{
			["CPLocalList"] = "default",
		}, -- end of ["Su-25T"]
		["SHAHED_136"] = {},
		["CJS Super Hornets Player"] = 
		{
			["abDetent"] = 0,
			["canopyReflections"] = 0,
			["hmdEye"] = 1,
			["CPLocalList"] = "default",
			["F18RealisticTDC"] = true,
			["mfdReflections"] = 0,
		}, -- end of ["CJS Super Hornets Player"]
		["Ka-50_3"] = 
		{
			["Ka50TrimmingMethod"] = 0,
			["Ka50RudderTrimmer"] = false,
			["hmdEye"] = 1,
			["Ka50PedalsYawReqReset"] = false,
			["CPLocalList"] = "default",
			["helmetCircleDisplacement"] = 11,
		}, -- end of ["Ka-50_3"]
		["Su35S"] = 
		{
			["SU35SPROG03FLR"] = 2,
			["SU35SPROG03FLI"] = 3,
			["SU35SPROG05CHBI"] = 0,
			["SU35SPROG02CHBI"] = 3,
			["SU35SPROG05CHN"] = 4,
			["SU35SPROG05FLI"] = 1,
			["SU35SPROG01CHI"] = 3,
			["SU35SPROG04FLI"] = 2,
			["SU35SPROG05FLN"] = 4,
			["SU35SPROG03CHI"] = 2,
			["SU35SPROG02TYPE"] = 1,
			["Su30MKMavionicsType"] = 0,
			["SU35SPROG05CHR"] = 3,
			["SU35SPROG01CHN"] = 4,
			["SU35SPROG02FLN"] = 1,
			["SU35SCHAFFBINGO"] = 10,
			["SU35SPROG03FLN"] = 4,
			["SU35SPROG05FLR"] = 3,
			["SU35SPROG04TYPE"] = 1,
			["SU35SPROG03CHN"] = 1,
			["SU35SPROG04FLR"] = 3,
			["SU35SPROG01CHR"] = 3,
			["Su30MKMfmType"] = 1,
			["SU35SPROG02CHI"] = 2,
			["SU35SPROG02FLI"] = 2,
			["SU35SPROG02CHR"] = 3,
			["SU35SPROG01CHBI"] = 0,
			["Su30SMavionicsType"] = 1,
			["Su30MKIfmType"] = 1,
			["CPLocalList_Su-35S"] = "default",
			["Su30SMfmType"] = 1,
			["Su30MKIavionicsType"] = 0,
			["Su30MKIroleType"] = 1,
			["SU35SPROG04CHN"] = 1,
			["SU35SPROG02FLBI"] = 3,
			["SU35SPROG01FLN"] = 1,
			["SU35SPROG04CHI"] = 2,
			["SU35SPROG04FLN"] = 4,
			["SU35SPROG03TYPE"] = 2,
			["SU35SPROG01TYPE"] = 3,
			["Su30MKAavionicsType"] = 0,
			["SU35SPROG02CHN"] = 3,
			["SU35SPROG03FLBI"] = 0,
			["SU35SPROG03CHBI"] = 3,
			["SU35SPROG04CHBI"] = 3,
			["Su30MKAfmType"] = 1,
			["SU35SFLAREBINGO"] = 10,
			["Su30MKAroleType"] = 1,
			["SU35SPROG01FLR"] = 1,
			["SU35SPROG02FLR"] = 1,
			["SU35SPROG01FLI"] = 2,
			["SU35SPROG05FLBI"] = 0,
			["SU35SPROG01FLBI"] = 3,
			["SU35SPROG04FLBI"] = 3,
			["SU35SPROG04CHR"] = 1,
			["Su30SMroleType"] = 1,
			["SU35SPROG05TYPE"] = 2,
			["SU35SPROG05CHI"] = 1,
			["SU35SPROG03CHR"] = 1,
			["Su30MKMroleType"] = 1,
		}, -- end of ["Su35S"]
		["tu_22"] = {},
		["Su-25"] = 
		{
			["CPLocalList"] = "default",
		}, -- end of ["Su-25"]
		["LeapMotion"] = 
		{
			["handUseThrottle"] = false,
			["handsHorizontalShift"] = 0,
			["enable"] = false,
			["set_debug"] = false,
			["handUseStick"] = false,
			["mouseClickSrc"] = 0,
		}, -- end of ["LeapMotion"]
		["B2_Spirit_block_30_V2"] = 
		{
			["CPLocalList_F-15C"] = "ANIME",
		}, -- end of ["B2_Spirit_block_30_V2"]
	}, -- end of ["plugins"]
	["format"] = 1,
	["sound"] = 
	{
		["main_output"] = "",
		["FakeAfterburner"] = false,
		["volume"] = 58,
		["headphones_on_external_views"] = true,
		["subtitles"] = true,
		["voiceChatInVolume"] = 50,
		["world"] = 45,
		["hear_in_helmet"] = true,
		["hp_output"] = "",
		["music"] = 0,
		["main_layout"] = "suround_7_1",
		["headphones"] = 70,
		["cockpit"] = 70,
		["voice_chat_output"] = "{0.0.0.00000000}.{fd76fa60-5337-4544-8e4b-dc4cd3cd9061}",
		["voice_chat"] = true,
		["GBreathEffect"] = true,
		["radioSpeech"] = true,
		["switches"] = 100,
		["play_audio_while_minimized"] = true,
		["voiceChatInSensitivity"] = -50,
		["microphone_use"] = 2,
		["voice_chat_input"] = "",
		["gui"] = 100,
	}, -- end of ["sound"]
	["views"] = 
	{
		["cockpit"] = 
		{
			["reflections"] = true,
			["mirrorsSequentialRendering"] = false,
			["avionicsMFDEveryFrame"] = true,
			["mirrors"] = false,
			["mirrorsEveryFrame"] = false,
			["mirrorsResolution"] = 1,
			["avionics"] = 3,
		}, -- end of ["cockpit"]
	}, -- end of ["views"]
} -- end of options
